Sage-Bionetworks/recover

- config/develop/namespaced/s3-to-glue-lambda.yaml
- config/develop/s3-to-glue-lambda-role.yaml
- config/prod/s3-to-glue-lambda-role.yaml
- config/prod/s3-to-glue-lambda.yaml
- src/lambda_function/README.md
- src/lambda_function/template.yaml
- templates/s3-to-glue-lambda-role.yaml
**Purpose:** Here, the lambda IAM role (S3ToGlueRole resource) is moved to its own stack so that it is independent of any other resources we are deploying. This way if we need to delete/redeploy the lambda stack the ARN of the S3ToGlueRole won’t change.
- S3 to Glue Lambda config and template
- S3 to Glue Lambda IAM role config and template
> [ETL-332] create lambda iam role

- config/develop/namespaced/s3-to-glue-lambda.yaml
- config/prod/s3-to-glue-lambda.yaml
- src/lambda_function/s3_to_glue/app.py
- src/lambda_function/template.yaml
- tests/test_s3_to_glue_lambda.py
**Purpose:** Originally the `lambda function` code hard coded in the `recover dev bucket` and `glue workflow` names and resulted in the tests having to test that those names exist which caused the tests to fail if you switched to the production account or deleted the workflow/changed the name. 
Now the lambda function is more robust as it takes the workflow and bucket names from the cloudformation templates as environment variables and the lambda stack also requires for the glue workflow to exist as a dependency so the tests can be removed.
> [ETL-361] Fix lambda function to use env var due to failing test

- .github/workflows/upload-and-deploy.yaml
- src/scripts/manage_artifacts/artifacts.py
**Purpose**: This PR does some simple refactoring. 
- Updates `upload-files` job in `upload-and-deploy` to use v3 of `action-pipenv-aws-setup` which allows the job's code to remove the actions that `action-pipenv-aws-setup` takes care of. 
- Updates artifacts script and `upload-and-deploy` to remove the hard coded repo name and instead use the environment NAMESPACE variable to set the namespace as the repo name when deploying main branch.
> Refactor artifacts github action (part of ETL-365)

- .github/workflows/upload-and-deploy.yaml
- Pipfile
- config/config.yaml
- config/develop/glue-job-JSONToParquet.yaml
- config/develop/glue-job-S3ToJsonS3.yaml
- src/lambda_function/README.md
- src/lambda_function/template.yaml
- templates/glue-job-JSONToParquet.j2
- templates/glue-job-S3ToJsonS3.yaml
**Purpose:** This PR follows the same logic as BridgeDownstream in that it launches stacks to the "recover" and feature branch namespaces of the recover **develop** account. 
This PR also parameterizes some of the python and glue versions used in the glue job stacks as we have varying python and glue versions to be used in the highest level stack config:`config/config.yaml`. Was unable to dynamically parameterize the lambda python runtime in the sam template to this stack because findings say it's not possible to pass this through to the lambda sam template.
- JSON to Parquet glue job: **Glue version 4.0** which supports **Python 3.10**
- S3 to Parquet glue job: **Python 3.9** (this is their highest available python for the glue python shell jobs) which means it can only use **Glue …
> [ETL-365] Launch stacks during push and PR to dev AWS account

- config/prod/s3-ingestion-bucket.yaml
- config/prod/s3-ingestion.yaml
Purpose: This creates the ingestion bucket for production data. (SYNAPSE_INPUT_SHARED_BUCKET)
This is the first bucket in the ingress pipeline for RECOVER project. We expect to receive data from Care Evolution in this bucket. This would be the raw version of the data, no QC, no QA - just all the data dump from Care Evolution. Both Care Evolution and Sage have access to this bucket
> [ETL-384] Add production s3 ingestion bucket

- config/prod/glue-job-JSONToParquet.yaml
- config/prod/glue-job-S3ToJsonS3.yaml
**Purpose**: Prod glue job stack configs need to be updated to use the new glue and python version parameters that dev glue job stack configs use.
This also **blocks** a lot of tickets that involve testing stack deployment in prod because currently the glue job stacks error out without this update
> [ETL-398] Add glue, python version params to relevant prod glue configs

- .github/workflows/cleanup.yaml
* Jobs occur in develop only upon branch deletion
* Delete namespaced stacks
* Delete namespaced folder in cloudformation bucket
> [ETL-380] Add cleanup workflow

- config/config.yaml
- config/prod/config.yaml
- config/prod/glue-job-role.yaml
- config/prod/s3-to-glue-lambda-role.yaml
- config/prod/s3-to-glue-lambda.yaml
**Purpose:** We recently created the new pre-ETL (input data) in the prod account, and now the prod stack configs need to be adjusted to use the new bucket. Here a stack group config was also created to house the prod specific bucket names for ease of use across all the prod stacks.
> [ETL-395] Modify prod stack configs to use new pre-ETL bucket name 

- config/develop/glue-job-role.yaml
- config/develop/namespaced/s3-to-glue-lambda.yaml
- config/develop/s3-input-bucket.yaml
- config/develop/s3-pilot-data.yaml
- config/develop/s3-to-glue-lambda-role.yaml
- templates/s3-bucket.yaml
* Pilot bucket stack renamed to recover-dev-input-bucket and bucket renamed to recover-dev-input-data
* Synapse permissions granted through use of `SynapseIds` parameter.
> [ETL-386] Rename pilot data bucket and link to Synapse

- .github/workflows/upload-and-deploy.yaml
- config/config.yaml
- config/develop/glue-job-JSONToParquet.yaml
- config/develop/glue-job-S3ToJsonS3.yaml
- config/develop/namespaced/s3-to-glue-lambda.yaml
- templates/glue-tables.j2
- templates/glue-workflow.j2
**Purpose:** This PR corrects the filepaths that various configs point to for their scripts so it follows this pattern now:
`<namespace>/src/...`. Our default namespace will be `main` when deploying to main branch as well as in production and CI/CD has been updated to reflect that.
> [ETL-382] Update folder structure of dev resources

- .github/workflows/upload-and-deploy.yaml
- config/develop/namespaced/s3-input-bucket-owner-txt.yaml
- config/develop/s3-input-bucket.yaml
- config/prod/namespaced/s3-input-bucket-owner-txt.yaml
- config/prod/s3-input-bucket.yaml
- config/prod/s3-processed-data-bucket-owner-txt.yaml
- config/prod/s3-processed-data-bucket.yaml
- templates/s3-bucket.yaml
- templates/s3-owner-txt.yaml
Some ancillary changes as well:
* Fixed syntax error in upload and deploy github workflow
* Split the `AWS::S3::Object` resource (owner.txt) into its own template from the S3 bucket template. Since the owner.txt is namespaced, but the bucket name is not, attempting to deploy the same bucket stack with a different namespace will result in the previous namespace's owner.txt being deleted. This appears to be a change necessitated by updates to sceptre. Previously, sceptre did not track custom resources like `AWS::S3::Object`, and so older namespaced resources were never deleted when the stack was deployed in a new namespace. That's since changed, hence the need to separate the Bucket resource from the owner.txt resource in the templates.
* Generalized the new `*-owner-txt.yaml` stacks so …
> [ETL-386] Grant Synapse access to dev pre-ETL bucket

- config/develop/s3-processed-data-bucket-owner-txt.yaml
- config/develop/s3-processed-data-bucket.yaml
- config/prod/s3-processed-data-bucket-owner-txt.yaml
- src/scripts/setup_external_storage/setup_external_storage.py
* Synapse granted permissions to dev parquet bucket (by modifying existing bucket stack) and owner.txt stack created
* Added functionality to `setup_external_storage` script to be able to use Synapse authentication token stored in SSM parameter.
* I tested it on this Synapse folder: https://www.synapse.org/#!Synapse:syn51284492
> [ETL-381] Grant Synapse access to dev parquet bucket

- config/develop/s3-input-bucket.yaml
- config/prod/s3-input-bucket.yaml
**Purpose:** Minor adjustment to add the ability to connect to Synapse and provide STS access to mirror the dev input bucket as well. Followup of this [PR](https://github.com/Sage-Bionetworks/recover/pull/27).
> [ETL-385] Grant prod input bucket synapse access

- .github/workflows/upload-and-deploy.yaml
**Purpose:** Currently this github action workflow will deploy to the "staging" namespace of production upon merge. If we decide we want to switch out of the staging testing workflow, it will be an easy change to have it deploy to the "main" namespace of prod. I also had the deployment to production as a separate job in case we wanted to do anything additional with that GH action job in the future.
Will squash the commits upon merge.
> [ETL-378] Launch all stacks to "staging" namespace in production account

- src/glue/jobs/json_to_parquet.py
- templates/glue-job-role.yaml
- templates/glue-workflow.j2
This PR covers removing deleted samples. (Removing duplicate samples was already implemented).
If a data type is a HealthKit data type, we check if it has a respective "deleted" table. If it does, we remove records which have a sample key in the "deleted" table. Otherwise, we carry on as usual without removing any records.
I also did some minor clean up in `templates/glue-job-role.yaml` and fixed a bug in `templates/glue-workflow.j2`
> [ETL-289] Remove deleted and duplicated samples

- src/lambda_function/README.md
- src/lambda_function/events/generate_test_event.py
- src/lambda_function/test-env-vars.json
This script can generate a S3 event notification test event for a single S3 object or for all S3 objects which exist directly under a specific S3 key prefix. Using this test event with our lambda simulates an object create/update event in an S3 bucket.
> [ETL-414] Add script to generate test S3 event notification

- config/develop/namespaced/s3-to-glue-lambda.yaml
- config/prod/namespaced/s3-to-glue-lambda.yaml
- src/lambda_function/s3_to_glue/app.py
- src/lambda_function/template.yaml
- tests/test_s3_to_glue_lambda.py
Effectively a rewrite of our S3 to Glue Lambda to use S3 event notifications. We skirt the owner.txt issues identified in the JIRA ticket by ignoring any objects which contain "owner.txt" in their name.
> [ETL-434] Modify S3 to Glue Lambda code to use S3 event notifications

- tests/Dockerfile
- tests/README.md
- tests/conftest.py
- tests/test_setup_external_storage.py
**Purpose:** This fixes the failing integration test for `setup_external_storage.py` and allows for the addition of command line arguments for running the test so that you are able to test STS access for multiple synapse folders that had STS access setup rather than a hard coded folder.
> [ETL-374] Fix failing test for setup_external_storage

- templates/s3-bucket.yaml
This bucket policy update blocks any type of access to a Synapse connected S3 bucket (pre/post ETL buckets) if:
* The request region is not us-east-1 OR
* The request comes from IAM or Support services.
Side note: IAM and Support are global services that have a physical endpoint in us-east-1, so it's not strictly necessary to list them here. But if we ever reuse this code in a different region it's important to allow access to these services.
> [ETL-435] Deny Synapse-connected bucket access outside us-east-1

- config/develop/namespaced/s3-input-bucket-owner-txt.yaml
- config/prod/namespaced/s3-input-bucket-owner-txt.yaml
Allows the service account to use the pre-ETL bucket in both develop and production as a Synapse external storage location.
> Include digital health service account in owner.txt

- config/develop/s3-processed-data-bucket-owner-txt.yaml
- config/prod/s3-processed-data-bucket-owner-txt.yaml
Related to #53 .
Let's allow digital health to use the processed data buckets as Synapse external storage locations.
> Add digital health service account to processed bucket owner.txt

- .github/workflows/upload-and-deploy-to-prod-main.yaml
- .github/workflows/upload-and-deploy.yaml
- src/lambda_function/s3_event_config/template.yaml
This ticket was for work needed to configure the S3 event trigger on the S3 to Glue lambda. Since this only occurs in prod/main, I've written a separate github workflow which deploys to prod/main and configures this trigger. This workflow is run whenever we push a semantically versioned tag to this repo.
> [ETL-446] Add upload-and-deploy-to-prod-main workflow

- tests/README.md
- tests/conftest.py
- tests/test_setup_external_storage.py
**Purpose:** This PR fixes the test(s) in `test_setup_external_storage.py` so that it properly tests if STS access credentials can give you list bucket access to a STS-enabled synapse folder.
> [ETL-483] Fix testing of bucket access via STS token credentials

- .github/workflows/README.md
- .github/workflows/upload-and-deploy-to-prod-main.yaml
- .github/workflows/upload-and-deploy.yaml
- src/lambda_function/s3_to_glue/events/generate_test_event.py
- tests/Dockerfile
- tests/Dockerfile.aws_glue_3
- tests/Dockerfile.aws_glue_4
- tests/README.md
- tests/test_compare_parquet_datasets.py
**Purpose:** This integrates all of our RECOVER tests into our github workflow `upload-and-deploy`. This composes of a some jobs:
`nonglue-unit-tests`:
- One job runs the non-glue tests under Python 3.9
`pytest-docker`:
- One job creates and uploads the dockerfile for AWS glue 3.0
- One job creates and uploads the dockerfile for AWS glue 4.0
`glue-unit-tests`:
- One job runs the tests under AWS glue 3.0
- One job runs the tests under AWS glue 4.0
Some outstanding questions are: 
Created a temporary test dev folder for these: `syn51079325`
Yes, this process works. Json to parquet already has a process in place to automatically archive old datasets and clear the workspace.
Depends on #60
> [ETL-327] Integrate RECOVER tests into CI/CD

- .github/workflows/upload-and-deploy.yaml
Submits all production data to the staging namespace's pipeline if the github ref is main.
> [ETL-407] Add integration tests for prod/staging

- src/glue/jobs/s3_to_json.py
- tests/test_s3_to_json.py
In addition to the Garmin transforms, I refactored the S3 to JSON job to be more functional. What used to just be
* `write_file_to_json_dataset`
has been split up into three different functions:
* `transform_json` - which takes care of any inserts/updates to the JSON data
* `transform_object_to_array_of_objects` - which is a helper function for `transform_json`
* `get_output_filename` - which takes care of filename / S3 object name formatting.
As a result of refactoring in the job, the tests have been refactored as well. Some tests were deleted and replaced with a more specific test.
> [ETL-505] Add Garmin transforms to S3 to JSON job

- config/develop/namespaced/s3-ingestion-bucket-owner-txt.yaml
- config/prod/namespaced/s3-ingestion-bucket-owner-txt.yaml
Synapse already has read/write access to the ingestion bucket, so the only thing to do to enable the use of the bucket as an external storage location is to write an owner.txt.
In develop, owner.txt is written to `main`.
In prod, owner.txt is written to the bucket root. This is where production data (e.g., `adults\/v1` and `pediatric\/v1`) already live.
> Add an owner.txt to the ingestion bucket

- templates/glue-job-JSONToParquet.j2
- templates/glue-workflow.j2
Reorganizes the primary workflow by running JSON to Parquet jobs in groups determined by their data type. Jobs are run in this order:
1. Non-device specific jobs (EnrolledParticipants, SymptomLog)
2. HealthKit jobs
3. Fitbit jobs
4. Google jobs
5. Garmin jobs
A job group is triggered if every job in the previously run job group succeeds. Structuring the JSON to Parquet jobs like this does increase the total workflow run time (the pilot data processing time increased from 13 minutes to 27 minutes) - since not as many jobs are being run in parallel. But it does put a lot less stress on our rate limits and we're less likely to get our jobs killed because we have exceeded the rate limit.
I've also increased the JSON to Parquet job default timeout to 12 hours from 2 hours.
> [ETL-521] Run JSON to Parquet jobs in groups

- config/develop/namespaced/s3-event-config-lambda.yaml
- config/develop/namespaced/sqs-queue.yaml
- config/prod/namespaced/s3-event-config-lambda.yaml
- config/prod/namespaced/sqs-queue.yaml
- src/lambda_function/s3_event_config/README.md
- src/lambda_function/s3_event_config/app.py
- src/lambda_function/s3_event_config/template.yaml
- templates/sqs-queue.yaml
- tests/test_s3_event_config_lambda.py
**Purpose:** This PR contains initial work done as part of [ETL-532](https://sagebionetworks.jira.com/browse/ETL-532) which led us to move forward with using SQS queue.
This PR only does the following:
- Sets up a working SQS queue that can receive messages from S3 pre-ETL bucket
- Updates the S3 event config lambda so that the S3 pre-ETL bucket can send S3 notifications to a SQS queue
[ETL-532]: https://sagebionetworks.jira.com/browse/ETL-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ETL-535] Set up SQS to receive S3 event notification

- config/develop/namespaced/glue-workflow.yaml
- config/prod/namespaced/glue-workflow.yaml
- src/glue/jobs/json_to_parquet.py
- src/glue/jobs/s3_to_json.py
- src/glue/resources/table_columns.yaml
- src/lambda_function/s3_to_glue/events/generate_test_event.py
- templates/glue-tables.j2
- templates/glue-workflow.j2
- tests/test_json_to_parquet.py
- tests/test_json_to_parquet/TestFlatDataType_20230512.ndjson
- tests/test_json_to_parquet/TestFlatDataType_20230612.ndjson
- tests/test_json_to_parquet/TestFlatDataType_Deleted_20230514.ndjson
- tests/test_json_to_parquet/TestFlatInsertedDateDataType_20230512.ndjson
- tests/test_json_to_parquet/TestFlatInsertedDateDataType_20230612.ndjson
- tests/test_json_to_parquet/TestNestedDataType_20230512.ndjson
- tests/test_json_to_parquet/TestNestedDataType_20230612.ndjson
- tests/test_s3_to_json.py
- Added `cohort` as a partition in our Glue table schemas.
- This requires us to include `cohort` as a property in our JSON. I also did some light refactoring around `get_part_path` in the S3 to JSON job.
- To add these partitions to our table, we need a Glue crawler. I've added one to crawl every data type.
- Updated test data to reflect the way data is organized in production (e.g., in `adults_v1` and `pediatric_v1` directories). Updated test event generation script so that it does not include these "directories" as individual events.
- Updated tests
> [ETL-533] Add `cohort` to data as partition

- config/develop/namespaced/s3-event-config-lambda.yaml
- config/prod/namespaced/s3-event-config-lambda.yaml
- src/lambda_function/s3_to_glue/events/generate_test_event.py
Rather than S3 events, we will send an SQS event wrapping one or more S3 events to our lambda.
Needs to be rebased on the work happening in #77 before merging.
> [ETL-537] Modify lambda event generation script to produce SQS events

- templates/sqs-queue.yaml
The behavior is as follows:
1. If Lambda raises an exception, the message will be sent back to the primary SQS queue up to 3 times before sending that message to the dead letter queue
2. Once the message is in the DLQ, it will be available for up to 2 weeks (the maximum allowed value) until we do a manual redrive of the message back to the primary SQS queue. If the message hasn't been processed after 2 weeks it disappears and will need to be added back to the primary queue either manually (more likely we would generate our own SQS event and send it directly to the Lambda) or by depositing the data in S3 again.
The DLQ doesn't need its own queue policy. It has permissions to receive and redrive messages to the primary queue on account of the primary queue's `RedrivePolicy`.
> [ETL-538] Add dead letter queue for our SQS queue

- src/lambda_function/s3_to_glue/app.py
- tests/test_s3_to_glue_lambda.py
> [ETL-561] Unquote S3 key name before submitting to Glue

- .github/workflows/upload-and-deploy.yaml
- config/develop/namespaced/s3-to-glue-lambda.yaml
- config/prod/namespaced/s3-to-glue-lambda.yaml
- src/lambda_function/s3_to_glue/app.py
- src/lambda_function/s3_to_glue/template.yaml
- src/lambda_function/s3_to_glue/test-env-vars.json
- templates/glue-workflow.j2
- tests/test_s3_to_glue_lambda.py
The important changes happen in [templates/glue-workflow.j2](https://github.com/Sage-Bionetworks/recover/compare/main...etl-568#diff-1ebab210688d33c708f526cb255445c7481a82ab71d012279d4b362c5c712963). This PR splits our workflow into two workflows:
1. S3 to JSON, which is triggered on-demand by the lambda and can run with infinite concurrency.
2. JSON to Parquet, which has a scheduled trigger (default 2 AM UTC / 7 PM PT) and is limited to 1 run at a time. The trigger is only activated if we are deploying to the `main` namespace (so as to not waste resources triggering the pipeline every day on our development stacks).
> [ETL-558] Decouple S3 to JSON workflow from JSON to Parquet workflow

- src/lambda_function/s3_event_config/app.py
- tests/test_json_to_parquet.py
- tests/test_s3_event_config_lambda.py
**Problem:**
1. When running lamdba_function `s3_event_config` new notifications could not be added to an S3 bucket, instead the notification configuration was always overwritten.
2. When deleting a NotificationConfiguration for a specific type ALL notification types were deleted.
**Solution:**
A) Adding notifications:
1) If a bucket has no `NotificationConfiguration` then create the config
2) If a bucket has a `NotificationConfiguration` but no matching
"{destination_arn}" for the "{destination_type}" then add the config
3) If a bucket has a `NotificationConfiguration` and a matching
"{destination_arn}" for the "{destination_type}":
3a) If the config is the same then do nothing
3b) If the config is different then overwrite the matching config
B) Deleting notifications - Only deleting the …
> [ETL-553] Allow merging of notification configs

- src/lambda_function/s3_event_config/app.py
In the lambda function to add event notifications pass `SkipDestinationValidation=True` in the `put_bucket_notification_configuration` call
> [ETL-575] Pass SkipDestinationValidation=True

- src/glue/jobs/s3_to_json.py
- src/scripts/consume_logs/consume_logs.py
- tests/test_consume_logs.py
- tests/test_s3_to_json.py
Changes:
* `src/glue/jobs/s3_to_json.py`
- Disabled propagation of LogRecords to root logger so that log messages contain _only_ the JSON formatted log emitted by the ECS log handler. This enables us to use Cloudwatch Metrics Insights to query our JSON.
- Updated tests since there is a pytest bug where the caplog fixture only captures logs emitted by the root logger.
- Included the workflow run ID as the `process.parent.pid` in the logger context so that every log message can be associated with a specific workflow run.
* `src/scripts/consume_logs.py`
- Initial commit
- Has tests
- The first half (see `main`) is general functionality that will run an arbitrary query over a timeframe and log group that you specify and group those logs by their workflow run. The second half is functionality …
> [ETL-568] Script to compare read/write record count from S3 to JSON logs

- .github/workflows/upload-and-deploy.yaml
Problem:
Previously we were manually creating test events to test the whole pipeline - instead we wanted the entire flow to handle this.
Solution:
Updating the integration test step to do an `aws cp` command to copy the test ingestion data
Testing:
See comment section of https://sagebionetworks.jira.com/browse/ETL-562 to see the whole flow having ran
> [ETL-562] Copy test data for integration testing

- CONTRIBUTING.md
- README.md
Things to look out for:
- incorrect information
- incomplete information
- additional documentation we can link out to, or information which is redundant with documentation elsewhere.
- broken links
> [ETL-574] Add CONTRIBUTING.md

- templates/glue-job-JSONToParquet.j2
This is approximately the largest timeout we could use while keeping the entire workflow time under ~22-24 hours.
> Increase JSON to Parquet timeout

- config/develop/namespaced/glue-job-JSONToParquet.yaml
- config/prod/namespaced/glue-job-JSONToParquet.yaml
- src/glue/jobs/json_to_parquet.py
- src/glue/jobs/s3_to_json.py
- templates/glue-job-JSONToParquet.j2
- tests/Dockerfile.aws_glue_4
- tests/test_json_to_parquet.py
- tests/test_json_to_parquet/TestFlatInsertedDateDataType_20230512.ndjson
- tests/test_json_to_parquet/TestFlatInsertedDateDataType_20230612.ndjson
Summary of changes:
---
* `src/glue/jobs/json_to_parquet.py`
* `tests/test_json_to_parquet.py`
Whenever a read, write, or transform operation is done with the data, we record the number of records for each `export_end_date` (which acts as an identifier for the original export). To support this functionality, functions which did any reading/writing/transforming were split up to be more atomic. Each of these functions requires a `record_counts` and `logger_context` object, which is passed to the function responsible for doing the counting: `count_records_for_event`.
Since there are typically multiple read/write/transform events per data type, we accumulate these within `record_counts` throughout the job. As the very last step in the job, we concatenate each of these event-specific counts …
> [ETL-580] JSON to Parquet - Write record count of each export to S3 

- src/glue/jobs/json_to_parquet.py
- tests/test_json_to_parquet.py
TLDR: Parameter types are hard and I should check if things work in dev before pulling into prod
> [ETL-589] Fix parameter type in delete_objects call

- src/glue/resources/table_columns.yaml
Waiting on response to [this JIRA comment](https://sagebionetworks.jira.com/browse/ETL-587?focusedCommentId=192507), but if my assumption is correct, `EOPReason` and `EOPRemoveData` belong in the `CustomFields` object.
> [ETL-587] Add fields EOPReason, EOPRemoveData, and IsMainSleep

- config/develop/namespaced/s3-event-config-lambda.yaml
- config/develop/namespaced/s3-to-glue-lambda-role.yaml
- config/develop/namespaced/s3-to-glue-lambda.yaml
- config/develop/namespaced/sqs-input-to-intermediate.yaml
- config/develop/namespaced/sqs-input-to-raw.yaml
- config/prod/namespaced/s3-event-config-lambda.yaml
- config/prod/namespaced/s3-to-glue-lambda-role.yaml
- config/prod/namespaced/s3-to-glue-lambda.yaml
- config/prod/namespaced/sqs-input-to-intermediate.yaml
- config/prod/namespaced/sqs-input-to-raw.yaml
Most of the changes involve renaming some parameters and stack names related to our original SQS queue (the one that's a go between for the input bucket and S3 to JSON Glue workflow). This was originally just named `sqs-queue` (stack name `sqs-S3ToLambda`), so I renamed the stack name and the file itself to `sqs-input-to-intermediate` to differentiate it from the new `sqs-input-to-raw` stack.
> [ETL-610] Add SQS queue for input to raw buckets processing

- .github/workflows/cleanup.yaml
- .github/workflows/upload-and-deploy-to-prod-main.yaml
- .github/workflows/upload-and-deploy.yaml
- src/lambda_function/s3_event_config/app.py
- tests/test_s3_event_config_lambda.py
Significant changes in the S3 event config lambda to support indexing individual configurations based on their S3 prefix/suffix overlap.
`.github/workflows/upload-and-deploy-to-prod-main.yaml` and `.github/workflows/upload-and-deploy.yaml`
* Delete the potentially preexisting notification configuration for a namespace before creation.
`src/lambda_function/s3_event_config/app.py`
* We introduce three new classes that abstract the API objects relevant to S3 event notifications:
- `NotificationConfiguration`: creates a common interface for interacting with individual notification configurations.
- `NotificationConfigurationType`: subsets the Enum class to restrict the types allowed for a `NotificationConfiguration` to `Queue`, `Topic`, and `LambdaFunction`.
- …
> [ETL-628] Rework S3 event config lambda

- src/glue/jobs/json_to_parquet.py
- src/glue/resources/table_columns.yaml
* Update index fields
* If parent parquet dataset has `ParticipantID` field, propagate that to the child
* Small change to the FitbitEcg schema to include the export start and end date fields
> [ETL-631] Update index fields with `ParticipantIdentifier` and propagate participant id fields

- src/glue/jobs/json_to_parquet.py
- tests/test_json_to_parquet.py
Primary changes are L192-208 where we swap the old (and faulty) sort + drop duplicate method of removing duplicates with the new window + sort + rank + filter method.
I also did some refactoring to make things a little more intuitive:
* `drop_table_duplicates` and `drop_deleted_healthkit_data` now return Spark DataFrames rather than Glue DynamicFrames. These functions already produced DataFrames so I removed the final cast as a DynamicFrame to simplify things. We cast back to a DynamicFrame on L662 since both branches of the conditional (relationalize+write else write) take a DynamicFrame as input.
* Mostly as a consequence of the above refactor, rather than deriving the data type from the table name in non-`main` functions I derive the data type once in `main` and pass that as an …
> [ETL-644] Update `drop_table_duplicates` function to use new method

- config/develop/namespaced/lambda-dispatch-role.yaml
- config/develop/namespaced/lambda-dispatch.yaml
- config/develop/namespaced/lambda-s3-event-config.yaml
- config/develop/namespaced/sns-dispatch-policy.yaml
- config/develop/namespaced/sns-dispatch.yaml
- config/develop/namespaced/sns-input-policy.yaml
- config/develop/namespaced/sns-input.yaml
- config/develop/namespaced/sqs-input-to-dispatch.yaml
- config/develop/namespaced/sqs-input-to-intermediate.yaml
- config/prod/namespaced/lambda-dispatch-role.yaml
- config/prod/namespaced/lambda-dispatch.yaml
- config/prod/namespaced/lambda-s3-event-config.yaml
- config/prod/namespaced/sns-dispatch-policy.yaml
- config/prod/namespaced/sns-dispatch.yaml
- config/prod/namespaced/sns-input-policy.yaml
- config/prod/namespaced/sns-input.yaml
- config/prod/namespaced/sqs-input-to-dispatch.yaml
- config/prod/namespaced/sqs-input-to-intermediate.yaml
- src/lambda_function/dispatch/README.md
- src/lambda_function/dispatch/app.py
- src/lambda_function/dispatch/template.yaml
- templates/lambda-dispatch-role.yaml
- templates/sns-topic-policy.yaml
- templates/sns-topic.yaml
- tests/test_lambda_dispatch.py
A lot of stacks were created/refactored as part of this PR, so here's a diagram to make things easier to understand:
Major changes include:
* A new Dispatch Lambda which is responsible for dispatching each JSON in an export as a separate job. These jobs will eventually be handled by the (to be implemented) Dispatch to Raw Lambda where each JSON will be decompressed and uploaded to the Raw S3 bucket.
* A refactor of the existing stacks responsible for propagating new exports to Glue. Now that we have two SQS queues subscribed to the SNS topic which is published to by our S3 input bucket, we need to name these things more precisely.
Some implementation patterns of note:
* I split the `AWS::SNS::TopicPolicy` from the `AWS::SNS::Topic` in the SNS stacks. This is useful because (for example) …
> [ETL-634] Implement Dispatch Lambda

- .github/workflows/upload-and-deploy.yaml
* Rather than copying over all input data, only copy the 28 (~2 weeks from each cohort) most recent exports to the namespaced location in the input bucket.
* The S3 URI of these 28 exports is uploaded to the S3 cloudformation bucket under the key `{namespace}/integration_test_exports.json` as a JSON array. This is for later reference in the comparison jobs. e.g.,
```
[
"s3://recover-dev-input-data/pilot-data/adults_v1/2023-01-12T22--02--17Z_77fefff8-b0e2-4c1b-b0c5-405554c92368",
"s3://recover-dev-input-data/pilot-data/adults_v1/2023-01-03T20--19--27Z_6fb88c91-eb34-4278-a603-4de03dfd9c70",
"s3://recover-dev-input-data/pilot-data/pediatric_v1/2023-06-26T22_35_22Z_8ae9d391-5c5d-4d79-bdce-6d86314caf8c",
...
]
```
* We now initiate integration tests for staging data by copying over exports …
> [ETL-647] Only submit most recent ~2 weeks of exports for integration tests

- src/glue/jobs/json_to_parquet.py
- src/glue/jobs/s3_to_json.py
- src/glue/resources/table_columns.yaml
- tests/test_json_to_parquet.py
- tests/test_s3_to_json.py
We didn't have `*_Deleted` tables for some HealthKit data types, which caused L255 of `src/glue/jobs/json_to_parquet.py` to raise a caught exception rather than removing deleted records for that data type. This only affected the `HealthKitV2Heartbeat` data type since we haven't received deleted records for any other HealthKit data type besides `HealthKitV2Samples`, which we already had a corresponding `*_Deleted` table for.
In addition to adding these new tables, I updated a few lines in `src/glue/jobs/s3_to_json.py`. In particular, the addition of the `HealthKitV2Samples_Deleted` and `HealthKitV2Statistics_Deleted` data types to the `DATA_TYPES_WITH_SUBTYPE` has the effect of adding the subtype included in the JSON file name into the JSON itself as a `Type` field. This field is not …
> [ETL-653] Add corresponding deleted data type table for all HealthKit data types

- config/develop/namespaced/s3-to-glue-lambda.yaml
- config/prod/namespaced/s3-to-glue-lambda.yaml
- src/lambda_function/s3_to_glue/template.yaml
> [ETL-656] Limit input-to-intermediate Lambda batch size to 1

- .pre-commit-config.yaml
- Pipfile
- config/develop/namespaced/glue-workflow.yaml
- config/prod/namespaced/glue-workflow.yaml
- src/glue/jobs/compare_parquet_datasets.py
- templates/glue-workflow.j2
- tests/Dockerfile.aws_glue_3
- tests/conftest.py
- tests/test_compare_parquet_datasets.py
The purpose of this PR is to update the comparison job that compares parquet datasets between `staging` and `main` so that it incorporates the changes in #115 where we only submit the most recent ~2 weeks of exports for integration testing of running our staging pipeline all the way through. 
See [JIRA Ticket](https://sagebionetworks.jira.com/browse/ETL-648) for the full description and reasoning but essentially we pull the data type / cohort / export_end_date from the JSON array that contains the exports to be used in the integration test: `s3://{cloudformation_bucket_name}/{namespace}/integration_test_exports.json`, then use those values to filter the production parquet datasets (the ones in `main` namespace) before running the comparisons.
There's also an extra layer of difficulty …
> [ETL-648] Modify comparsion job to only consider records from recent exports

- .pre-commit-config.yaml
- pyproject.toml
- src/glue/jobs/compare_parquet_datasets.py
- src/glue/jobs/json_to_parquet.py
- src/glue/jobs/s3_to_json.py
- src/lambda_function/dispatch/app.py
- src/lambda_function/s3_event_config/app.py
- src/lambda_function/s3_to_glue/app.py
- src/lambda_function/s3_to_glue/events/generate_test_event.py
- src/scripts/consume_logs/consume_logs.py
- src/scripts/manage_artifacts/artifacts.py
- src/scripts/manage_artifacts/clean_for_integration_test.py
- src/scripts/setup_external_storage/setup_external_storage.py
- tests/conftest.py
- tests/test_compare_parquet_datasets.py
- tests/test_consume_logs.py
- tests/test_lambda_dispatch.py
- tests/test_s3_event_config_lambda.py
- tests/test_s3_to_glue_lambda.py
- tests/test_s3_to_json.py
- tests/test_setup_external_storage.py
**Problem:**
1. No linting was set up in the precommit config
**Solution:**
1. Set up the black formatter and isort to run in pre-commit
> [ETL-670] Setup and run pre-commit for all files

- .github/workflows/upload-and-deploy.yaml
- tests/Dockerfile.aws_glue_3
**Purpose:** This is a draft PR because this is just a temp. solution. There is a known discrepancy between the `glibc` version used by the aws glue docker images (2.26) and `glibc` version used by all of the AWS actions  versionswhich is expecting >= 2.27. Until the aws glue docker images are updated to use Node js version 20 (which uses glibc >= 2.27), this is the discovered workaround. [See blog post for more info](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/). This discussion gives a good view into the issue itself: https://github.com/actions/checkout/issues/1809#issue-2389388431
This solution is still temp. because ideally aws updates their aws glue docker images to use node js 20.
See [JIRA …
> [ETL-671] Update to use older node version on aws actions

- .github/workflows/upload-and-deploy.yaml
- src/scripts/manage_artifacts/clean_for_integration_test.py
Problem:
1. We do want to run the cleanup on the `main` directory of the dev branch
Solution:
1. Updating the workflow so the job is triggered and we are able to clean the `main` directory
Testing:
1. Will be looking at the workflow run
> [ETL-670] Adjust cleanup job to run on `main` directory of dev env

- .github/workflows/upload-and-deploy-to-prod-main.yaml
- .github/workflows/upload-and-deploy.yaml
- snowflake/objects/deploy.sql
When merging a PR into main, we deploy changes to a `staging` Snowflake environment. Because we can only do variable substitution in a stage path using CLI variables when invoking our entrypoint `snowflake/objects/deploy.sql` from the command line, I've split the `environment` variable into an `environment` and `git_branch` variable. Both must be specified.
> [ETL-659] Enable any branch to be deployed to any environment

- src/scripts/manage_artifacts/clean_for_integration_test.py
**Problem:**
1. There is a maximum of 1000 objects that can return from a single call to `list_objects_v2`
**Solution:**
1. Using a pagination to loop over all objects in the bucket/prefix
**Testing:**
1. To review the action runs
> [ETL-670] Update code to paginate over all results

- .github/workflows/cleanup.yaml
I did not use the right reference
> Fix Snowflake cleanup

- snowflake/objects/database/recover/schema/parquet/deploy.sql
- snowflake/objects/database/recover/schema/parquet/procedure/copy_into_table_from_stage.sql
- snowflake/objects/database/recover/schema/parquet/procedure/deploy.sql
- snowflake/objects/database/recover/schema/parquet/stage/deploy.sql
- snowflake/objects/database/recover/schema/parquet/stage/parquet_dev_s3.sql
- snowflake/objects/database/recover/schema/parquet/stage/parquet_prod_s3.sql
- snowflake/objects/deploy.sql
For each of our Parquet data types, we create a stored procedure which can do a `COPY INTO` operation from the S3 location of that data type into a Snowflake table. Additionally, I've added an external stage for our development S3 bucket. We do not call these stored procedures as part of the deployment process. Instead, we will call the procedures using Tasks (future work). 
* `snowflake/objects/database/recover/schema/parquet/procedure/copy_into_table_from_stage.sql`
This is the stored procedure logic. This procedure will copy data from a specific stage (S3) location, but can copy into any Snowflake table (specified by the `target_table` parameter).
* `snowflake/objects/database/recover/schema/parquet/procedure/deploy.sql`
This handles the logic of deploying the above procedure for each …
> [ETL-676] Create data loading procedure for each parquet datatype

- snowflake/scripts/copy_into_each_parquet_table.sql
This script will load data into each of our Parquet tables one by one. It's expected to take a few hours to run on an xsmall warehouse.
You can test this script yourself by creating a testing branch from this branch, pushing your new branch (triggering the Snowflake deployment), copying dev Parquet data from the `main` namespace over to your namespace in S3 `s3://recover-dev-processed-data/my_test_branch/parquet/`, and then using the Snowflake CLI to invoke this script:
```
snow sql -f snowflake/scripts/copy_into_each_parquet_table.sql -D "database_name=recover_my_test_branch" -D "schema_name=parquet" 
```
It's important to note that the current behavior of this script and the stored procedure which it invokes is meant to fulfill the needs of doing a one-time initial load of our Parquet …
> [ETL-677] Add bootstrap script for Snowflake Parquet tables

- src/scripts/compress_json/compress_json.py
Recombines the NDJSON part sets which we wrote to our intermediate bucket and uploads a gzipped NDJSON to an adjacent location.
Each part set is located at:
`s3://<bucket-name>/<namespace>/json/dataset={dataset}/cohort={cohort}/`
where `{dataset}` is the dataset identifier (datatype),  and `{cohort}` is either 'adults_v1' or 'pediatric_v1'. Each file in the part set is named:
`{file_identifier}.part{part_number}.ndjson`
Each combined and gzipped part set is written to:
`s3://<bucket-name>/<namespace>/compressed_json/dataset={dataset}/cohort={cohort}/{file_identifier}.ndjson.gz`
> [ETL-674] Add script to compress intermediate JSON

- src/glue/jobs/s3_to_json.py
- tests/test_s3_to_json.py
In addition to partitioning and writing JSON to JSON datasets as "part files", e.g., 
```
FitbitIntradayCombined_20220111-20230103.part0.ndjson
FitbitIntradayCombined_20220111-20230103.part1.ndjson
...
```
Write the JSON as a gzip archive to a separate `compressed_json` S3 prefix.
```
FitbitIntradayCombined_20220111-20230103.ndjson.gz
```
This PR is meant to ease the transition towards exclusively using compressed JSON data as the input to JSON to Parquet. Hence, there are a few changes here which are meant to be refactored later on once we remove the logic for writing uncompressed part files. The primary changes are to the function `write_file_to_json_dataset` with some supporting changes in helper functions.
You can get a more concrete feel for how this affects the behavior of S3 to …
> [ETL-673] Upload compressed JSON as part of S3 to JSON

- config/develop/namespaced/lambda-raw-role.yaml
- config/develop/namespaced/lambda-raw.yaml
- config/develop/namespaced/sqs-dispatch-to-raw.yaml
- config/prod/namespaced/lambda-raw-role.yaml
- config/prod/namespaced/lambda-raw.yaml
- config/prod/namespaced/sqs-dispatch-to-raw.yaml
- src/lambda_function/dispatch/app.py
- src/lambda_function/raw/README.md
- src/lambda_function/raw/app.py
- src/lambda_function/raw/template.yaml
- templates/lambda-raw-role.yaml
- tests/test_lambda_raw.py
Adds resources:
- Lambda: The raw Lambda, which polls the dispatch-to-raw SQS queue and writes compressed JSON to the raw S3 bucket.
- IAM Role: An IAM role for the above Lambda.
Raw Lambda compresses JSON data contained in an export (zip archive) from the input S3 bucket and uploads it to the raw S3 bucket. It makes heavy use of Python file objects and multipart uploads and can download/compress/upload with a relatively low, fixed memory overhead with respect to the size of the uncompressed JSON. For example, during testing I was able to process a 450 MB (uncompressed) JSON file with a max memory used of 345 MB.
> [ETL-636] Raw Lambda

- src/lambda_function/raw/app.py
- tests/test_lambda_raw.py
The raw Lambda did not differentiate between “Deleted” and non-deleted datatypes. For example, HealthKitV2Heartbeat_Samples_Deleted_20230701-20230702.ndjson.gz was written to the HealthKitV2Heartbeat S3 prefix. I fixed that.
> [ETL-688] Handle "Deleted" data types correctly in raw lambda

- .github/workflows/upload-and-deploy.yaml
- config/develop/namespaced/events-rule-raw-sync.yaml
- config/develop/namespaced/lambda-dispatch.yaml
- config/develop/namespaced/lambda-raw-sync-role.yaml
- config/develop/namespaced/lambda-raw-sync.yaml
- config/prod/namespaced/events-rule-raw-sync.yaml
- config/prod/namespaced/lambda-dispatch.yaml
- config/prod/namespaced/lambda-raw-sync-role.yaml
- config/prod/namespaced/lambda-raw-sync.yaml
- src/lambda_function/raw_sync/README.md
- src/lambda_function/raw_sync/app.py
- src/lambda_function/raw_sync/template.yaml
- templates/events-rule.yaml
- templates/lambda-raw-sync-role.yaml
- tests/test_lambda_raw_sync.py
This Lambda verifies that the input and raw S3 buckets are synchronized. It's triggered by a Cloudwatch Events rule at midnight UTC each day.
This is accomplished by verifying that all non-zero sized JSON in each export in the input S3 bucket have a corresponding object in the raw S3 bucket. Because we only download the central directory, located near the end of a zip archive, verification can be done extremely quickly and without needing to download most of the export. If a JSON file from an export is found to not have a corresponding object in the raw bucket, the export is submitted to the raw Lambda (via the dispatch SNS topic) for processing.
> [ETL-611] Raw sync lambda

- src/lambda_function/raw_sync/app.py
- tests/test_lambda_raw_sync.py
I pulled the logic in `main` which derives the data type from the file name into its own function so that we can write tests for it. I also did some linting.
> [ETL-693] Add function for parsing data type to raw-sync lambda

- src/lambda_function/raw_sync/app.py
- tests/test_lambda_raw_sync.py
Fixes a bug introduced in #144
> Use raw key prefix to construct raw key

- src/lambda_function/raw_sync/app.py
- tests/test_lambda_raw_sync.py
Some of the paths in our log messages contained double forward slashes in the path because they were not being formatted correctly. Any path constructions have been replaced with `os.path.join(...)` calls.
> Log formatting fixes for raw-sync lambda

- .github/workflows/upload-and-deploy-to-prod-main.yaml
- .github/workflows/upload-and-deploy.yaml
Fixes bug described in ticket.
> [ETL-694] Specify python-version in actions/setup-python
