- config/config.yaml
- config/develop/config.yaml
- config/develop/glue-job-S3ToJsonS3.yaml
- config/develop/glue-job-role.yaml
- config/develop/glue-workflow.yaml
- config/develop/s3-pilot-data.yaml
- config/prod/glue-job-S3ToJsonS3.yaml
- config/prod/glue-job-role.yaml
- config/prod/glue-workflow.yaml
- src/glue/jobs/s3_to_json.py
- templates/glue-job-S3ToJsonS3.yaml
- templates/glue-job-role.yaml
- templates/glue-workflow.yaml
* New stacks for S3 to JSON Glue job, The IAM role for the job, and the Glue workflow which will serve as our primary (and likely only) workflow.
* New stack for pilot data S3 bucket.
* S3 to JSON job implemented
> [ETL-283] S3 to JSON job

- Pipfile
- Pipfile.lock
- config/config.yaml
- config/develop/cfn-s3objects-macro.yaml
- config/prod/cfn-s3objects-macro.yaml
- config/prod/s3-processed-data-bucket.yaml
- src/scripts/setup_external_storage/setup_external_storage.py
- templates/s3-bucket.yaml
- tests/Dockerfile
- tests/README.md
- tests/test_setup_external_storage.py
**Purpose:** Set up parquet datasets for STS access
- Bucket Policy of the S3 bucket template modified so that it writes an owner.txt to the parquet dataset location.
- Script for setting up STS and the storage location to be the S3 location of the parquet datasets
> [ETL-340] Set up sts access

- src/glue/jobs/s3_to_json.py
I noticed that the HealthKitV2Statistics data type has a subtype included in its file name. I'm handling this the same way as we already handle the subtype in HealthKitV2Samples.
> Write type of HealthKitV2Statistics to JSON

- tests/test_s3_to_json.py
This should have been part of #18
> Update S3 to JSON tests

- .github/workflows/upload-and-deploy.yaml
- config/develop/glue-job-JSONToParquet.yaml
- config/develop/glue-job-S3ToJsonS3.yaml
- config/develop/namespaced/s3-to-glue-lambda.yaml
- src/scripts/manage_artifacts/artifacts.py
**Purpose:** This PR allows us to upload artifacts to the prod and dev S3 cloudformation buckets as part of the upload_and_deploy CI/CD workflow in github using the new OIDC integration.
> [ETL-336] Upload artifacts

- .github/workflows/cleanup.yaml
> Add permissions for OIDC to cleanup action

- config/develop/config.yaml
- config/develop/glue-job-JSONToParquet.yaml
- config/develop/glue-job-role.yaml
- config/develop/namespaced/glue-job-S3ToJsonS3.yaml
- config/develop/namespaced/glue-tables.yaml
- config/develop/namespaced/glue-workflow.yaml
- config/develop/namespaced/s3-to-glue-lambda.yaml
- config/develop/s3-cloudformation-bucket.yaml
- config/develop/s3-ingestion.yaml
- config/develop/s3-input-bucket.yaml
- config/develop/s3-intermediate-bucket.yaml
- config/develop/s3-processed-data-bucket.yaml
- config/develop/s3-to-glue-lambda-role.yaml
- config/prod/glue-job-JSONToParquet.yaml
- config/prod/glue-job-role.yaml
- config/prod/namespaced/glue-job-S3ToJsonS3.yaml
- config/prod/namespaced/glue-tables.yaml
- config/prod/namespaced/glue-workflow.yaml
- config/prod/namespaced/s3-to-glue-lambda.yaml
- config/prod/s3-cloudformation-bucket.yaml
- config/prod/s3-ingestion.yaml
- config/prod/s3-input-bucket.yaml
- config/prod/s3-intermediate-bucket.yaml
- config/prod/s3-processed-data-bucket.yaml
**Purpose:** This PR updates and syncs up the dependencies in the prod and dev stack configs. 
This includes:
- Adding required dependencies where needed
- Removing dependencies pointing to buckets and instead referencing bucket names using `stack_group_config` to reduce redundancy and spinning up resources when unnecessary
> [ETL-401] Update dependencies for stack configs in prod and dev accounts

- config/develop/s3-ingestion.yaml
- config/prod/s3-ingestion.yaml
Allow Pranav to access the ingestion bucket
> [ETL-447] Provide access to pranav

- src/glue/jobs/json_to_parquet.py
Archives existing datasets in S3 by moving them to a timestamped subfolder within an "archive" folder. The format of the timestamped subfolder is:
```
{year}_{month}_{day}_{workflow_run_id}
```
If the dataset does not exist at `key_prefix` or if the dataset is empty, no action will be taken.
Also added some logging statements to `add_index_to_table`.
> [ETL-466] Archive existing parquet datasets before writing parquet

- src/lambda_function/s3_to_glue/events/generate_test_event.py
This allows us to pass a custom list of s3 objects needing processing. We can create a list using, for example, a command like `aws s3 ls ... | awk '{print $4}' > objects_to_process`.
> Add --input-key-file parameter to test event generation script

- src/glue/jobs/s3_to_json.py
- tests/test_s3_to_json.py
Some JSON files are too large to have all of their records kept in memory before being written to the resulting transformed NDJSON file. To avoid an OOM error, we do the transformations and write the records in blocks.
> [ETL-517] Write JSON records as NDJSON in blocks

- src/glue/jobs/s3_to_json.py
- tests/test_s3_to_json.py
* Add a part number to NDJSON file names
* Any NDJSON file which is greater than the max file size (~100 MB by default) is uploaded to the JSON dataset. Any remaining data will be written to the next NDJSON part.
> [ETL-519] Limit file size of NDJSON written to JSON datasets

- templates/s3-bucket.yaml
This update affects the following stacks:
```
config/prod/s3-intermediate-bucket.yaml
config/prod/s3-processed-data-bucket.yaml
config/prod/s3-input-bucket.yaml
config/prod/s3-cloudformation-bucket.yaml
config/develop/s3-intermediate-bucket.yaml
config/develop/s3-processed-data-bucket.yaml
config/develop/s3-input-bucket.yaml
config/develop/s3-cloudformation-bucket.yaml
```
> [ETL-525] Grant Phil, Rixing identity-central accounts access to S3

- src/glue/jobs/s3_to_json.py
- tests/test_s3_to_json.py
* Splits `write_file_to_json_dataset` into two functions:
- `write_file_to_json_dataset` contains the logic for writing the JSON part file locally
- `_upload_file_to_json_dataset` contains the logic for uploading the JSON part file to S3 and acts as a helper function for `write_file_to_json_dataset`.
* `_upload_file_to_json_dataset` handles the upload and potential deletion of the JSON part file, and is called whenever the current part file being written to exceeds the allowed file size (default ~100 MB) or after we have exhausted all data from the input JSON file and must upload the final part file.
> [ETL-550] Upload and delete part files immediately after final write

- templates/glue-job-JSONToParquet.j2
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-jobs-job.html#aws-glue-api-jobs-job-Job-Job-WorkerType
> [ETL-585] Upgrade worker type for HealthKitV2Samples and FitbitIntraday to G.2X

- .github/workflows/cleanup.yaml
- .github/workflows/upload-and-deploy-to-prod-main.yaml
- .github/workflows/upload-and-deploy.yaml
So we don't run into silly errors.
> Specify default warehouse in Snowflake config

- src/glue/jobs/s3_to_json.py
I did not catch every instance in my previous PR where I was uploading files before the corresponding stream was closed. I also added an additional logging statement to verify that we are deleting files after upload.
> bug squashed: uploading part file before file stream closed

- templates/glue-job-JSONToParquet.j2
This is a fix for ETL-675, as described [here](https://sagebionetworks.jira.com/browse/ETL-675?focusedCommentId=220694)
> Add HealthKitV2Electrocardiogram type to large jobs

- .github/workflows/upload-and-deploy.yaml
I should have included this with #141
> clean up raw bucket before integration test

- .github/workflows/cleanup.yaml
missed this snowflake-cli-action call
> update snowflake-cli-action tag in cleanup
